# Generated by Django 3.0.5 on 2020-06-26 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20200626_0634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='names',
            name='url',
        ),
    ]
