# Generated by Django 3.0.5 on 2020-06-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_remove_names_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='nam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=264, unique=True)),
                ('last', models.CharField(max_length=264, unique=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='names',
        ),
    ]
